rd /S /Q Character
rd /S /Q Etc
rd /S /Q Item
rd /S /Q Map
rd /S /Q Mob
rd /S /Q Npc
rd /S /Q Reactor
rd /S /Q scripts
rd /S /Q Server
rd /S /Q Skill
rd /S /Q String

ln -s Character ../../rsvp-data/Character
ln -s Etc ../../rsvp-data/Etc
ln -s Item ../../rsvp-data/Item
ln -s Map ../../rsvp-data/Map
ln -s Mob ../../rsvp-data/Mob
ln -s Npc ../../rsvp-data/Npc
ln -s Reactor ../../rsvp-data/Reactor
ln -s scripts ../../rsvp-scripts
ln -s Server ../../rsvp-data/Server
ln -s Skill ../../rsvp-data/Skill
ln -s String ../../rsvp-data/String